### ISSUE TITLE
☂️ Allow external agents to start embedded etcd and set readiness via HTTP API

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-wrapper#14]
**How to categorize this issue?**

/area quality robustness usability
/kind enhancement task

**What would you like to be added**:
I would like etcd-wrapper to allow external agents to start embedded etcd and set readiness via HTTP API. This will help simplify the etcd bootstrapping process for the backup sidecar, by allowing it to re-use the embedded etcd provided by etcd-wrapper for restoration, but with readiness set to false so that the etcd does not serve external traffic. Once restoration is successful and the etcd is deemed ready to serve traffic, then readiness can be set to true by the backup sidecar to allow external traffic.

Additionally, I would like etcd-wrapper to provide a mechanism for leadership change notifications, which can be consumed by the backup sidecar or any other external agent via a push or pull mechanism.

**Task List**:
- [ ] Leadership notification mechanism
- [ ] Expose http endpoint to start embedded etcd with config passed in POST call
- [ ] Expose http endpoint to set app readiness to ready/unready
